### ISSUE TITLE
Issue-Muestra direccion despliegue, saldo y dir. contratos. Pide confirmacion

Para automatizar:

   echo "confirmar" | brownie run deploy

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#105]
Automated Review Comments
Issues in scripts/deploy.py:
  - (9, 'Missing docstring for function')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (35, 'Missing docstring for function')
  - (37, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
