### ISSUE TITLE
Issue-Limitado de saldo: 10k tokens / dirección (hardcoded)

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#11]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (3, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
