### ISSUE TITLE
Issue-Migramos faucet a nueva dirección con 50% saldo de tokens.

El resto de los token se quedan en la dirección de despliegue
para migrarlos a un Layer2 con comisiones de red _mucho_ más
baratas que en mainnet.

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#113]
Automated Review Comments
Issues in scripts/new_faucet.py:
  - (8, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (103, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (121, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
