### ISSUE TITLE
Issue-Despliega en la red polygon

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#119]
Automated Review Comments
Issues in scripts/deploy_polygon.py:
  - (17, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (45, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
