### ISSUE TITLE
Issue-Reparto de tokens a los holders en Polygon por reyes

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#121]
Automated Review Comments
Issues in scripts/reyes.py:
  - (15, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
