### ISSUE TITLE
Issue-Quita dependencia de Openzeppelin

ERC20 es una interfaz sencilla.
No vale la pena tirar de openzeppelin para tener una interfaz con tan pocas línas.

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#15]
Automated Review Comments
Issues in contracts/Airdrop.sol:
  - (3, 'Line exceeds 80 characters')
  - (3, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
