### ISSUE TITLE
Issue-Compila en v0.6.6

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#19]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (31, 'TODO found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
