### ISSUE TITLE
Issue-Clarificadas fases

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#23]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
