### ISSUE TITLE
Issue-Asigna balance de tokens a quien despliega el contrato

Closes #1

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#27]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
