### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#3]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (10, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
