### ISSUE TITLE
Issue-Cada contrato a su propio directorio

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#44]
Automated Review Comments
Issues in contracts/Airdrop/Airdrop.sol:
  - (5, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
Issues in contracts/Ayusocoin/Ayusocoin.sol:
  - (11, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
