### ISSUE TITLE
Issue-Testing del contrato de Aidrop

Pendiente: Comprobar el evento

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#46]
Automated Review Comments
Issues in tests/test_airdrop.py:
  - (10, 'Missing docstring for function')
  - (24, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (44, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
