### ISSUE TITLE
Issue-_root puede cambiar el balance max. por direccion

Manejar un balance maximo es una de las cosas que se pueden
hacer muy facilmente con un smart contract.
Otra de las cosas que se pueden hacer es limitar las transacciones "directas"
a partir de un importe determinado sin pasar por un contrato especial
(por ejemplo, hacienda) para declarar movimiento de dinero.

Closes #4

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#58]
Automated Review Comments
Issues in contracts/Ayusocoin/Ayusocoin.sol:
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
Issues in tests/test_ayusocoin.py:
  - (15, 'Missing docstring for function')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (37, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
