### ISSUE TITLE
Issue-Funcionalidad "usuario root"

- La variable _root es privada. Cuesta ether usarla.
- Se emite un mensaje cuando se cambia _root
- _root puede cambiar los balances maximos si es iniciado por usuario.
- Funcion isRoot(address) para saber quien es root (pagando ether)

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#62]
Automated Review Comments
Issues in contracts/Ayusocoin/Ayusocoin.sol:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
Issues in tests/test_ayusocoin.py:
  - (2, 'Hardcoded string found')
  - (13, 'Missing docstring for function')
  - (17, 'Missing docstring for function')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (58, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
