### ISSUE TITLE
Issue-TestProxt contract para subir la cobertura

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#66]
Automated Review Comments
Issues in contracts/Test_proxy/Test_proxy.sol:
  - (5, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
