### ISSUE TITLE
Issue-Initial readme file

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#7]
Automated Review Comments
Issues in README.md:
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
