### ISSUE TITLE
Issue-Add: Feature para recuperar los tokens del contrato.

Contract: variable _root con el que despliega contrato.
Test: solo _root puede recuperar los tokens.

Closes #10 #11

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#80]
Automated Review Comments
Issues in contracts/Faucet.sol:
  - (8, 'Hardcoded string found')
Issues in tests/test_faucet.py:
  - (10, 'Missing docstring for function')
  - (33, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
