### ISSUE TITLE
Issue-Imports especificos de bronie. No more brownie.xyzt

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#82]
Automated Review Comments
Issues in tests/test_ayusocoin.py:
  - (9, 'Missing docstring for function')
  - (25, 'Hardcoded string found')
  - (27, 'Missing docstring for function')
  - (30, 'Hardcoded string found')
  - (34, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
