### ISSUE TITLE
Issue-Medidas de seguridad en transferFrom()

Subimos un poco el listón de seguridad:
- Trabajamos con una copia del allowance antes de modificarlo.
- Comprobamos que no hay interger underflow en el allowance (es un ataque sencillo)

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/Ayusocoin#9]
Automated Review Comments
Issues in contracts/Ayusocoin.sol:
  - (3, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (46, 'TODO found')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
